/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs345.deadwood;

import java.util.Scanner;

public class Deadwood {

    /*
    USAGE: Initializes and starts the game
     */
    public static void main(String[] args) {

        // asking for how many players:
        int numberOfPlayers = 4;
        if (args.length > 0) {
            try {
                numberOfPlayers = Integer.parseInt(args[0]);
            } catch (NumberFormatException e) {
                System.out.println("Usage: ./gradlew run --args \"NUM\", where NUM should be an integer between 2 and 8.");
                return ;
            }
            if (numberOfPlayers > 8 || numberOfPlayers < 2) {
                System.out.println("Usage: ./gradlew run --args \"NUM\", where NUM should be an integer between 2 and 8.");
                return ;
            }
        }

        DeadWoodModel model = new DeadWoodModel();
        Controller controller = new Controller(model);
        BoardView view = new BoardView(model, controller);
        view.init(numberOfPlayers);
        controller.startGame(numberOfPlayers);
    }
}
